# fly.toml app configuration file generated for rough-cloud-9294 on 2023-11-15T12:59:05+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-cloud-9294"
primary_region = "arn"

[build]

[env]
  PORT = "3000" # add this

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
